<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.1 (Python 3.8.5 on win32)" generated="20200809 21:12:48.112" rpa="false">
<suite id="s1" name="TC01" source="C:\Projetos\Automation Practice\TestCases\TC01.robot">
<test id="s1-t1" name="Cenário 01: Garantir que ao clicar no header está direcionando para a homepage">
<kw name="Dado que esteja na tela HOME do site Automation Practice">
<msg timestamp="20200809 21:12:48.143" level="FAIL">No keyword with name 'Dado que esteja na tela HOME do site Automation Practice' found.</msg>
<status status="FAIL" starttime="20200809 21:12:48.143" endtime="20200809 21:12:48.143"></status>
</kw>
<status status="FAIL" starttime="20200809 21:12:48.141" endtime="20200809 21:12:48.144" critical="yes">No keyword with name 'Dado que esteja na tela HOME do site Automation Practice' found.</status>
</test>
<status status="FAIL" starttime="20200809 21:12:48.114" endtime="20200809 21:12:48.152"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="TC01">TC01</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200809 21:12:48.139" level="ERROR">Error in file 'C:\Projetos\Automation Practice\TestCases\TC01.robot' on line 2: Resource file 'C:\Projetos\Automation Practice\TestCases..\Resources\main.resource' does not exist.</msg>
</errors>
</robot>
